"""Preparatory backtester for OOS prediction validation.

This module uses Qlib's ``risk_analysis`` for performance analytics and keeps
the portfolio simulation intentionally lightweight. It consumes the prediction
parquet generated by ``XGBoostTrainer`` during the test/OOS segment.

Because the project currently reads market data directly from parquet instead
of a Qlib binary provider, this class does not call Qlib's exchange simulator.
It emulates the common Qlib ``TopkDropoutStrategy`` idea on daily predictions:
hold top-k names, drop the weakest n names every rebalance day, and use the
realized next-day label as the portfolio return.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

import numpy as np
import pandas as pd
from qlib.contrib.evaluate import risk_analysis

from utils import PROJECT_ROOT, load_backtester_config, load_trainer_config


class PreparatoryBacktester:
    """Run OOS strategy backtest from prediction parquet.

    The default config is ``conf/preparatory_backtester_config.json``. If
    ``start_time`` / ``end_time`` are absent in the backtester config, the class
    reads the trainer config and uses its ``test`` segment as the OOS period.
    """

    def __init__(self, config_path: str | Path | None = None, **overrides: Any) -> None:
        self.config_path = config_path
        self.config = self._apply_overrides(load_backtester_config(config_path), overrides)

        self.trainer_config_path = self.config.get("trainer_config_path")
        self.trainer_config = load_trainer_config(self.trainer_config_path) if self.trainer_config_path else {}

        self.prediction_path = Path(self.config["prediction_path"])
        self.output_dir = Path(self.config["output_dir"])
        self.account = float(self.config.get("account", 100000000.0))
        self.freq = self.config.get("freq", "day")
        self.benchmark = self.config.get("benchmark", "market_mean")
        self.strategy_config = dict(self.config.get("strategy", {}))
        self.exchange_kwargs = dict(self.config.get("exchange_kwargs", {}))
        self.columns = dict(self.config.get("columns", {}))
        self.score_col = self.columns.get("score", "pred")
        self.prediction_label_col = self.columns.get("label")
        self.return_label_col = self.columns.get("return_label", self.config.get("return_label_col", "label_1d"))
        self.return_col = self.columns.get("return", self.config.get("return_col", "return_1d"))
        # Keep the historical attribute name for downstream code; it now means
        # the realized 1-day return column used by the parquet backtest.
        self.label_col = self.return_col
        self.label_path = Path(
            self.config.get("label_path", PROJECT_ROOT / "data" / "generated_label" / "daily_labels")
        )
        self.save_positions = bool(self.config.get("save_positions", True))

        self.start_time, self.end_time = self._resolve_oos_period()

    @staticmethod
    def _apply_overrides(config: dict[str, Any], overrides: Mapping[str, Any]) -> dict[str, Any]:
        merged = dict(config)
        for key, value in overrides.items():
            if value is not None:
                merged[key] = value
        return merged

    def _resolve_oos_period(self) -> tuple[pd.Timestamp, pd.Timestamp]:
        start_time = self.config.get("start_time")
        end_time = self.config.get("end_time")

        if start_time is None or end_time is None:
            test_segment = self.trainer_config.get("segments", {}).get("test")
            if not test_segment:
                raise ValueError("Backtester start/end are missing and trainer config has no test segment")
            start_time = start_time or test_segment[0]
            end_time = end_time or test_segment[1]

        return pd.Timestamp(start_time), pd.Timestamp(end_time)

    def load_predictions(self) -> pd.DataFrame:
        """Load OOS scores and merge 1-day realized returns for backtest.

        The prediction parquet may contain labels with horizons other than
        1 day (for example ``label_5d`` used during model training).  Portfolio
        simulation should use next-day realized returns, so this method always
        joins ``return_label_col`` (default: ``label_1d``) from
        ``data/generated_label/daily_labels`` and exposes it as ``return_col``
        (default: ``return_1d``).
        """

        if not self.prediction_path.exists():
            raise FileNotFoundError(f"Prediction file does not exist: {self.prediction_path}")

        pred_df = pd.read_parquet(self.prediction_path)
        if not isinstance(pred_df.index, pd.MultiIndex):
            raise ValueError("Prediction parquet must use MultiIndex(datetime, instrument)")
        if pred_df.index.names != ["datetime", "instrument"]:
            pred_df.index = pred_df.index.set_names(["datetime", "instrument"])

        if self.score_col not in pred_df.columns:
            raise KeyError(f"Prediction file missing required score column: {self.score_col}")

        dates = pred_df.index.get_level_values("datetime")
        mask = (dates >= self.start_time) & (dates <= self.end_time)
        pred_df = pred_df.loc[mask, [self.score_col]]
        pred_df = pred_df.replace([np.inf, -np.inf], np.nan).dropna(subset=[self.score_col])

        return_df = self.load_return_labels()
        pred_df = pred_df.join(return_df, how="inner")
        pred_df = pred_df.replace([np.inf, -np.inf], np.nan).dropna(subset=[self.score_col, self.return_col])
        return pred_df.sort_index()

    def load_return_labels(self) -> pd.DataFrame:
        """Load ``label_1d`` style returns from generated daily label files."""

        if not self.label_path.exists():
            raise FileNotFoundError(f"Label path does not exist: {self.label_path}")

        files = self._label_files_for_period()
        if not files:
            raise FileNotFoundError(
                f"No label parquet files found in {self.label_path} for {self.start_time.date()} ~ {self.end_time.date()}"
            )

        frames = []
        required = ["trade_date", "ts_code", self.return_label_col]
        for file_path in files:
            frame = pd.read_parquet(file_path, columns=required)
            frames.append(frame)
        label_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame(columns=required)
        missing = [col for col in required if col not in label_df.columns]
        if missing:
            raise KeyError(f"Daily label files missing required columns: {missing}")

        label_df = label_df.rename(columns={"trade_date": "datetime", "ts_code": "instrument", self.return_label_col: self.return_col})
        label_df["datetime"] = pd.to_datetime(label_df["datetime"].astype(str), format="%Y%m%d", errors="coerce")
        label_df = label_df.dropna(subset=["datetime", "instrument", self.return_col])
        mask = (label_df["datetime"] >= self.start_time) & (label_df["datetime"] <= self.end_time)
        label_df = label_df.loc[mask, ["datetime", "instrument", self.return_col]]
        return label_df.set_index(["datetime", "instrument"]).sort_index()

    def _label_files_for_period(self) -> list[Path]:
        """Return daily label parquet files whose filename date overlaps OOS period."""

        files: list[Path] = []
        for file_path in self.label_path.rglob("*.parquet"):
            try:
                file_date = pd.to_datetime(file_path.stem, format="%Y%m%d")
            except ValueError:
                files.append(file_path)
                continue
            if self.start_time <= file_date <= self.end_time:
                files.append(file_path)
        return sorted(files)

    def run(self, save: bool = True) -> dict[str, Any]:
        """Run backtest and optionally save artifacts."""

        pred_df = self.load_predictions()
        report_df, positions_df = self._simulate_topk_dropout(pred_df)
        analysis = self._analyze(report_df)

        if save:
            self.save_outputs(report_df=report_df, positions_df=positions_df, analysis=analysis)

        return {"report": report_df, "positions": positions_df, "analysis": analysis}

    def _simulate_topk_dropout(self, pred_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
        topk = int(self.strategy_config.get("topk", 50))
        n_drop = int(self.strategy_config.get("n_drop", 5))
        open_cost = float(self.exchange_kwargs.get("open_cost", 0.0))
        close_cost = float(self.exchange_kwargs.get("close_cost", 0.0))
        cost_rate = open_cost + close_cost + float(self.exchange_kwargs.get("impact_cost", 0.0))

        holdings: set[str] = set()
        old_weights: dict[str, float] = {}
        reports: list[dict[str, Any]] = []
        positions: list[dict[str, Any]] = []
        account_value = self.account

        for trade_date, day_df in pred_df.groupby(level="datetime", sort=True):
            day_df = day_df.droplevel("datetime")
            scores = day_df[self.score_col].dropna()
            labels = day_df[self.return_col]
            if scores.empty:
                continue

            holdings = self._rebalance_holdings(scores=scores, holdings=holdings, topk=topk, n_drop=n_drop)
            selected = [inst for inst in holdings if inst in labels.index and pd.notna(labels.loc[inst])]
            if not selected:
                continue

            new_weights = {inst: 1.0 / len(selected) for inst in selected}
            turnover = self._calc_turnover(old_weights=old_weights, new_weights=new_weights)
            cost = turnover * cost_rate
            gross_return = float(labels.loc[selected].mean())
            net_return = gross_return - cost
            benchmark_return = self._calc_benchmark_return(labels)
            excess_return = net_return - benchmark_return
            account_value *= 1.0 + net_return

            reports.append(
                {
                    "datetime": trade_date,
                    "return": net_return,
                    "gross_return": gross_return,
                    "benchmark": benchmark_return,
                    "excess_return": excess_return,
                    "cost": cost,
                    "turnover": turnover,
                    "account_value": account_value,
                    "holdings_count": len(selected),
                }
            )
            if self.save_positions:
                positions.extend(
                    {
                        "datetime": trade_date,
                        "instrument": inst,
                        "weight": weight,
                        "return_1d": float(labels.loc[inst]),
                    }
                    for inst, weight in new_weights.items()
                )
            old_weights = new_weights

        report_df = pd.DataFrame(reports).set_index("datetime") if reports else pd.DataFrame()
        positions_df = pd.DataFrame(positions)
        if not positions_df.empty:
            positions_df = positions_df.set_index(["datetime", "instrument"]).sort_index()
        return report_df, positions_df

    @staticmethod
    def _rebalance_holdings(scores: pd.Series, holdings: set[str], topk: int, n_drop: int) -> set[str]:
        if topk <= 0:
            raise ValueError("strategy.topk must be positive")

        ranked_desc = scores.sort_values(ascending=False)
        if not holdings:
            return set(ranked_desc.head(topk).index)

        valid_holdings = set(scores.index).intersection(holdings)
        if n_drop > 0 and valid_holdings:
            sell_names = scores.loc[list(valid_holdings)].sort_values(ascending=True).head(n_drop).index
            valid_holdings -= set(sell_names)

        new_holdings = set(valid_holdings)
        for instrument in ranked_desc.index:
            if len(new_holdings) >= topk:
                break
            new_holdings.add(instrument)
        return new_holdings

    @staticmethod
    def _calc_turnover(old_weights: Mapping[str, float], new_weights: Mapping[str, float]) -> float:
        instruments = set(old_weights).union(new_weights)
        return float(sum(abs(new_weights.get(inst, 0.0) - old_weights.get(inst, 0.0)) for inst in instruments))

    def _calc_benchmark_return(self, labels: pd.Series) -> float:
        # Current parquet prediction artifact has no benchmark index return.
        # ``market_mean`` is a practical OOS cross-sectional benchmark.
        if self.benchmark == "market_mean":
            return float(labels.dropna().mean())
        if self.benchmark in labels.index:
            return float(labels.loc[self.benchmark])
        return 0.0

    def _analyze(self, report_df: pd.DataFrame) -> dict[str, Any]:
        if report_df.empty:
            return {}

        return {
            "return": self._risk_to_dict(risk_analysis(report_df["return"], freq=self.freq)),
            "benchmark": self._risk_to_dict(risk_analysis(report_df["benchmark"], freq=self.freq)),
            "excess_return": self._risk_to_dict(risk_analysis(report_df["excess_return"], freq=self.freq)),
            "summary": {
                "start_time": str(report_df.index.min().date()),
                "end_time": str(report_df.index.max().date()),
                "trading_days": int(len(report_df)),
                "final_account_value": float(report_df["account_value"].iloc[-1]),
                "mean_turnover": float(report_df["turnover"].mean()),
                "mean_cost": float(report_df["cost"].mean()),
                "mean_holdings_count": float(report_df["holdings_count"].mean()),
            },
            "config": self.config,
        }

    @staticmethod
    def _risk_to_dict(risk_df: pd.DataFrame) -> dict[str, float]:
        if isinstance(risk_df, pd.Series):
            raw = risk_df.to_dict()
        elif risk_df.shape[1] == 1:
            raw = risk_df.iloc[:, 0].to_dict()
        else:
            raw = risk_df.to_dict()
        return PreparatoryBacktester._json_safe(raw)

    @staticmethod
    def _json_safe(obj):
        if isinstance(obj, dict):
            return {str(k): PreparatoryBacktester._json_safe(v) for k, v in obj.items()}
        if isinstance(obj, (list, tuple)):
            return [PreparatoryBacktester._json_safe(v) for v in obj]
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, (np.floating,)):
            return float(obj)
        if isinstance(obj, Path):
            return str(obj)
        if pd.isna(obj):
            return None
        return obj

    def save_outputs(self, report_df: pd.DataFrame, positions_df: pd.DataFrame, analysis: Mapping[str, Any]) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        report_df.to_parquet(self.output_dir / "backtest_report.parquet")
        if self.save_positions and not positions_df.empty:
            positions_df.to_parquet(self.output_dir / "positions.parquet")
        with (self.output_dir / "analysis.json").open("w", encoding="utf-8") as f:
            json.dump(self._json_safe(dict(analysis)), f, ensure_ascii=False, indent=2)


__all__ = ["PreparatoryBacktester"]
